# Credenciales de base de datos
DB_HOST = "localhost"
DB_PORT = "5432"
DB_USER = "postgres"
DB_PASSWORD = "123456"
DB_NAME = "postgres"

# API Keys (si las necesitas en el dashboard)
API_KEY = "f7ffc8ef09528c6629869e249c9c307a"
WEATHERSTACK_BASE_URL = "https://api.weatherstack.com"
CIUDADES = "Bogota,Medellin,Cali,Barranquilla,Cartagena"